[upstream]
peer_address = "preview-node.world.dev.cardano.org:30002"
network_magic = 2
is_testnet = true

[storage]
path = "./tmp/rolldb"
wal_size = 1000

[sync]
pull_batch_size = 200

[submit]
prune_height = 10000

[genesis]
byron_path = "./byron.json"
shelley_path = "./shelley.json"
alonzo_path = "./alonzo.json"

[mithril]
aggregator = "https://aggregator.pre-release-preview.api.mithril.network/aggregator"
genesis_key = "5b3132372c37332c3132342c3136312c362c3133372c3133312c3231332c3230372c3131372c3139382c38352c3137362c3139392c3136322c3234312c36382c3132332c3131392c3134352c31332c3233322c3234332c34392c3232392c322c3234392c3230352c3230352c33392c3233352c34345d"

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_path = "dolos.socket"
magic = 2

[relay]
listen_address = "[::]:30013"

[logging]
max_level = "info"
