[upstream]
peer_address = "preview-node.world.dev.cardano.org:30002"
network_magic = 2

[rolldb]
path = "./tmp/rolldb"
k_param = 10000

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_address = "127.0.0.1:30013"
magic = 2
