[upstream]
block_production_interval = 5

[storage]
version = "v3"
path = "data"

[storage.wal]
backend = "redb"

[storage.state]
backend = "fjall"

[storage.archive]
backend = "redb"

[storage.index]
backend = "fjall"

[genesis]
byron_path = "./byron.json"
shelley_path = "./shelley.json"
alonzo_path = "./alonzo.json"
conway_path = "./conway.json"
force_protocol = 9

[sync]
pull_batch_size = 100
sync_limit = "NoLimit"

[submit]

[serve.grpc]
listen_address = "[::]:5164"
permissive_cors = true

[serve.minibf]
listen_address = "[::]:3164"
permissive_cors = true

[serve.trp]
listen_address = "[::]:8164"
max_optimize_rounds = 10
permissive_cors = true

[chain]
type = "cardano"

[chain.track]
account_state = true
asset_state = true
pool_state = true
epoch_state = true
drep_state = true
datum_state = true
proposal_logs = true
tx_logs = true
account_logs = true
pool_logs = true
epoch_logs = true

[[chain.custom_utxos]]
ref = [
    "8d910e3a410a353787d50a708e24c6ba2cc2b6b86ec6d8cb5bf9bbec20bfc937",
    0,
]
era = 7
cbor = [
    162,
    0,
    88,
    29,
    96,
    13,
    209,
    114,
    185,
    177,
    134,
    111,
    217,
    81,
    59,
    150,
    252,
    190,
    55,
    138,
    45,
    90,
    220,
    127,
    180,
    153,
    148,
    158,
    136,
    101,
    213,
    62,
    223,
    1,
    27,
    0,
    0,
    0,
    23,
    72,
    118,
    232,
    0,
]

[[chain.custom_utxos]]
ref = [
    "2ecf77d32245449d50f7d07238eef4d4a5e16fe35ac6574d537f2d711088e8a4",
    0,
]
era = 7
cbor = [
    162,
    0,
    88,
    29,
    96,
    99,
    200,
    189,
    42,
    33,
    58,
    198,
    103,
    9,
    130,
    227,
    119,
    177,
    45,
    193,
    219,
    164,
    255,
    90,
    117,
    32,
    244,
    35,
    33,
    101,
    62,
    168,
    179,
    1,
    27,
    0,
    0,
    0,
    23,
    72,
    118,
    232,
    0,
]

[[chain.custom_utxos]]
ref = [
    "555b0c75b501599aa08445ad9c55bbfbacd4fa009fda77c89ee520d9f871180c",
    0,
]
era = 7
cbor = [
    162,
    0,
    88,
    29,
    96,
    39,
    235,
    105,
    9,
    255,
    217,
    126,
    240,
    214,
    19,
    171,
    227,
    182,
    10,
    73,
    122,
    109,
    242,
    160,
    119,
    142,
    29,
    159,
    77,
    89,
    27,
    87,
    144,
    1,
    27,
    0,
    0,
    0,
    23,
    72,
    118,
    232,
    0,
]

[telemetry]
enabled = true
otlp_endpoint = "http://localhost:4317"
service_name = "dolos"

[logging]
max_level = "DEBUG"
include_tokio = false
include_pallas = false
include_grpc = true
include_trp = false
include_minibf = false
