[upstream]
peer_address = "cardano-node-1:32000"
network_magic = 42
is_testnet = true

[storage]
version = "v1"
path = "data"
max_wal_history = 10000
max_chain_history = 10000

[genesis]
byron_path = "byron.json"
shelley_path = "shelley.json"
alonzo_path = "alonzo.json"
conway_path = "conway.json"
force_protocol = 9

[chain]
type = "cardano"

[chain.track]
account_state = true
asset_state = true
pool_state = true
epoch_state = true
drep_state = true
proposal_logs = true
tx_logs = true
account_logs = true
pool_logs = true
epoch_logs = true

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"

[serve.minibf]
listen_address = "[::]:3000"

[logging]
max_level = "DEBUG"
include_tokio = true
include_pallas = true
include_grpc = true
include_trp = true
include_minibf = true
