[upstream]
block_production_interval = 10

[storage]
version = "v3"
path = "data"

[storage.wal]
backend = "redb"
max_history = 10000

[genesis]
byron_path = "byron.json"
shelley_path = "shelley.json"
alonzo_path = "alonzo.json"
conway_path = "conway.json"
force_protocol = 6

[sync]
pull_batch_size = 100

[submit]
prune_height = 200

[serve.grpc]
listen_address = "[::]:50051"
permissive_cors = true

[serve.ouroboros]
listen_path = "dolos.socket"
magic = 2

[serve.trp]
listen_address = "[::]:8000"
max_optimize_rounds = 10
permissive_cors = true

[telemetry]
enabled = true
otlp_endpoint = "http://localhost:4317"
service_name = "dolos"

[logging]
max_level = "DEBUG"
include_pallas = false
include_grpc = false
