[upstream]
peer_address = "preprod-node.world.dev.cardano.org:30000"
network_magic = 1
network_id = 0

[rolldb]
path = "./tmp/rolldb"
k_param = 1000

[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_address = "localhost:30013"
magic = 0

[byron]
path = "./byron.json"
