name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    continue-on-error: true

    strategy:
      matrix:
        include:
          # don't change `Linux` or `x86_64` to avoid breaking the
          # install script because it relies on the `uname` outputs
          - release_for: Linux-x86_64
            build_on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            args: "--locked --release"

          # don't change `Linux` or `arm64` to avoid breaking the
          # install script because it relies on the `uname` outputs
          - release_for: Linux-arm64
            build_on: ubuntu-latest
            target: "aarch64-unknown-linux-gnu"
            args: "--locked --release --no-default-features"

          - release_for: Windows-x86_64
            build_on: windows-latest
            target: x86_64-pc-windows-msvc
            args: "--locked --release"
            ext: .exe

          # don't change `Darwin` or `x86_64` to avoid breaking the
          # install script because it relies on the `uname` outputs
          - release_for: Darwin-x86_64
            build_on: macOS-latest
            target: x86_64-apple-darwin
            args: "--locked --release"

          # don't change `Darwin` or `arm64` to avoid breaking the
          # install script because it relies on the `uname` outputs
          - release_for: Darwin-arm64
            build_on: macOS-latest
            target: aarch64-apple-darwin
            args: "--locked --release"

    runs-on: ${{ matrix.build_on }}

    steps:
      - name: install deps [MacOS]
        if: matrix.build_on == 'macOS-latest'
        run: |
          brew install openssl@1.1

      - name: checkout repository
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release"

      - name: build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: ${{ matrix.args }}
          strip: true

      - name: rename binaries
        run: |
          mv target/${{ matrix.target }}/release/dolos${{ matrix.ext }} dolos-${{ matrix.release_for }}${{ matrix.ext }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dolos-${{ matrix.release_for }}${{ matrix.ext }}

  docker:
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/txpipe/dolos
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/txpipe
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: .github/image/bin

      # we need to rename the artifact so that the name matches
      # the value that Docker uses for TARGET_ARCH to keep the
      # Dockerfile simple
      - name: Rename artifacts
        run: |+
          mv .github/image/bin/dolos-Linux-x86_64 .github/image/bin/dolos-Linux-amd64

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .github/image
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    needs: [build, docker]

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.16"

      - name: download artifacts
        id: "download"
        uses: actions/download-artifact@v3

      - name: set release notes
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.0
          git-chglog -c .github/chglog/release.yml $(git describe --tags) > RELEASE.md

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/*
          body_path: RELEASE.md
          draft: true
